mail_address: christelle.fraisse.rios@gmail.com
infile: /nfs/scistore03/bartogrp/cfraisse/dils_inferences/ARNOUX_solanaceae/PM/PM_synonymous_MD_HET-genes.fasta
region: noncoding
nspecies: 2
nameA: PM_CROP
nameB: PM_WILD
nameOutgroup: NA
useSFS: 1
config_yaml: /nfs/scistore03/bartogrp/cfraisse/dils_inferences/ARNOUX_solanaceae/PM/config_2pop-PM.yaml
timeStamp: PM-CROP-WILD
population_growth: variable
modeBarrier: bimodal
max_N_tolerated: 0.5
Lmin: 100
nMin: 4
mu: 0.00000001
rho_over_theta: 0.5
N_min: 0
N_max: 100000 
Tsplit_min: 0
Tsplit_max: 50000
M_min: 1
M_max: 20
